name: Benchmark CML
# FIXME: rename this file benchmarks.yaml and remove the other
#

# Benchmarks are expensive thus should be launched manually
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Repo reference (branch, tag or SHA)
        default: "main"
        required: true
        type: string

# Global environnement variables
env:
  # Github action url (used by slack notification)
  ACTION_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

# Jobs
jobs:
  prepare-scripts:
    name: Prepare scripts to launch on individual AWS instances
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    container:
      image: ubuntu:20.04
    outputs:
      commands: ${{ steps.prepare-commands.outputs.commands }}
      length: ${{ steps.prepare-commands.outputs.length }}
    env:
      PIP_INDEX_URL: ${{ secrets.PIP_INDEX_URL }}
      PIP_EXTRA_INDEX_URL: ${{ secrets.PIP_EXTRA_INDEX_URL }}
    steps:
      - name: Add masks
        run: |
          echo "::add-mask::${{ secrets.INTERNAL_PYPI_URL_FOR_MASK }}"
          echo "::add-mask::${{ secrets.INTERNAL_REPO_URL_FOR_MASK }}"
          echo "::add-mask::${{ secrets.INTERNAL_PYPI_URL }}"
          echo "::add-mask::${{ secrets.INTERNAL_REPO_URL }}"
      - name: Docker container related setup and git installation
        id: docker-git-config
        run: |
          TZ=Europe/Paris
          echo "TZ=${TZ}" >> "$GITHUB_ENV"
          ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone
          sed -i 's|^deb http://archive|deb http://fr.archive|g' /etc/apt/sources.list
          apt update && apt install git git-lfs -y

      # We don't need to specify the git-ref here since he are just generating the cli arguments 
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Set up Python
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5
        with:
          python-version: "3.9"

      - name: Install dependencies
        id: install-deps
        run: |
          ./script/make_utils/setup_os_deps.sh
          make setup_env

      - name: Prepare scripts to launch on individual AWS instances
        id: prepare-commands
        run: |
          source .venv/bin/activate
          COMMANDS=$(python3 ./script/actions_utils/generate_scripts_benchmark.py)
          export COMMANDS
          LENGTH=$(echo "${COMMANDS}" | jq '. | length')
          echo "${COMMANDS}"
          echo "${LENGTH}"
          echo "::set-output name=commands::${COMMANDS}"
          echo "::set-output name=length::${LENGTH}"

  run-job:
    needs: [prepare-scripts]
    secrets: inherit
    strategy:
      matrix:
        index: ${{ fromJson(needs.prepare-scripts.outputs.commands) }}
      max-parallel: ${{ fromJson(needs.prepare-scripts.outputs.length) }}
    uses: ./.github/workflows/single_benchmark.yaml
    with:
      command: ${{ matrix.index.command }}
      git-ref: ${{ github.event.inputs.git-ref }}

  slack-notification:
    runs-on: ubuntu-20.04
    needs: [run-job]
    steps:
      - name: Slack Notification
        if: ${{ always() }}
        continue-on-error: true
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_ICON: https://pbs.twimg.com/profile_images/1274014582265298945/OjBKP9kn_400x400.png
          SLACK_COLOR: ${{ needs.run-job.result }}
          SLACK_MESSAGE: "Benchmark action: (${{ env.ACTION_RUN_URL }}) ended with result: ${{ needs.run-job.result }}"
          SLACK_USERNAME: ${{ secrets.BOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

