# Trigger AWS ImageBuidler pipeline to produce an AmazonMachineImage (AMI) containing concrete-ml
name: Publish AWS AMI
on:
  release:
    types: [published]

jobs:
  # This job will trigger a build for Python3.9 only. A matrix strategy needs to be set up
  # if a build is needed for other version of Python, or even other platforms (ARM, M1).
  launch-ami-build:
    name: Launch AMI build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build pipeline via Slab
        run: |
          PAYLOAD='{"name": "zama-concrete-ml-${{ github.ref_name }}-py39-x86_64",\
          "description": "Zama Concrete ML ${{ github.ref_name }} (with Python 3.9 for x86_64 architecture)",\
          "region": "eu-west-3",\
          "image_pipeline_arn": ${{ secrets.AMI_PIPELINE_ARN }},\
          "distribution_configuration_arn": ${{ secrets.AMI_DISTRIB_CONFIG_ARN }}}'

          SIGNATURE="$(slab/scripts/hmac_calculator.sh ${PAYLOAD} '${{ secrets.JOB_SECRET }}')"

          curl -v -k \
          -H "Content-Type: application/json" \
          -H "X-Slab-Repository: ${{ github.repository }}" \
          -H "X-Slab-Command: build_aws_ami" \
          -H "X-Hub-Signature-256: sha256=${SIGNATURE}" \
          -d @${{ PAYLOAD }} \
          ${{ secrets.SLAB_URL }}

      - name: Slack Notification
        if: ${{ always() }}
        continue-on-error: true
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_ICON: https://pbs.twimg.com/profile_images/1274014582265298945/OjBKP9kn_400x400.png
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: "AWS AMI build pipeline triggered for concrete-ml ${{ github.ref_name }}"
          SLACK_USERNAME: ${{ secrets.BOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }
